### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ni-ko-o-kin** [elmcraft/elmcraft.org#20]
On this page:
https://elmcraft.org/lore/

the link to:
https://elmcraft.org/what-is-evan-working-on

returns:
Page not found

**Comment by supermario** [comment]
Thanks @ni-ko-o-kin – @Janiczek also just reported this, fixed in https://github.com/elmcraft/elmcraft.org/commit/5a5e3d644442e298784e2bfd1245eb5e7eab5845 a few minutes before you posted 😆
