### ISSUE TITLE
Add Japanese translation of the Elm guide?

### ISSUE THREAD

**Issue by agj** [elmcraft/elmcraft.org#28]
Under [Learn](https://elmcraft.org/learn) there's a link to the French translation of the Elm guide. I know of one other such translation, namely the Japanese one, which I just skimmed over and found to be of good quality (yes, I can read Japanese). The REPL works, too.

Wouldn't it be a nice addition to the resources?

https://guide.elm-lang.jp

**Comment by supermario** [comment]
@agj yes, that would be great! A PR is welcome :)
